# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install build dependencies for lz4
RUN apt-get update && apt-get install -y gcc liblz4-dev && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir fastmcp>=2.10.5 chepy>=7.3.0

# Set working directory
WORKDIR /app

# Copy application code
COPY . .

# Default command to run the MCP server over stdio
CMD ["python", "main.py"]
